import json
import os
import re

from groq import Groq

SYSTEM_PROMPT = (
    "You are a text provenance analyst. Assess whether the given text was "
    "likely written by a human or generated by AI. Respond ONLY with valid JSON "
    'in this exact format: {"ai_likelihood": <float 0.0-1.0>, "reasoning": "<brief>"} '
    "where 0.0 means definitely human-written and 1.0 means definitely AI-generated."
)


def _parse_score(raw: str) -> float:
    """Extract ai_likelihood from model response, with fallback parsing."""
    try:
        data = json.loads(raw)
        score = float(data["ai_likelihood"])
        return max(0.0, min(1.0, score))
    except (json.JSONDecodeError, KeyError, TypeError, ValueError):
        match = re.search(r"0\.\d+|1\.0|1|0", raw)
        if match:
            return max(0.0, min(1.0, float(match.group())))
        return 0.5


def get_llm_score(text: str) -> float:
    """
    Signal 1: LLM-based classification via Groq.
    Returns a score in [0.0, 1.0] where higher = more likely AI-generated.
    """
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key or api_key == "your_key_here":
        return _heuristic_fallback(text)

    client = Groq(api_key=api_key)
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": text},
        ],
        temperature=0.1,
        max_tokens=150,
    )
    raw = response.choices[0].message.content.strip()
    return _parse_score(raw)


def _heuristic_fallback(text: str) -> float:
    """Keyword-based fallback when Groq API key is not configured."""
    ai_phrases = [
        "it is important to note",
        "furthermore",
        "in conclusion",
        "paradigm shift",
        "stakeholders",
        "it is equally essential",
        "various sectors",
        "transformative",
    ]
    lower = text.lower()
    hits = sum(1 for phrase in ai_phrases if phrase in lower)
    base = min(0.3 + hits * 0.12, 0.95)
    if re.search(r"\b(i|my|me|ok|honestly|lol|ugh)\b", lower):
        base -= 0.25
    return max(0.05, min(0.95, base))
